### ISSUE TITLE
Try to show as much as posible of method.body on exception

### ISSUE THREAD

**Issue by NiKiZe** [telerik/JustDecompileEngine#13]
When an internal error happens no method body at all is generated, even if it was only one instruction that was unknown. Instead it should only mark failed IL with a comment about failure, but display the rest.
(Sorry if my understanding of the internals is completely wrong)

I would like to have/add a CommentStatement, and then output similar to the `// ISSUE` line from dotPeek, with The internal exception, and a possible explanation (instead of the current ExceptionStatement),
Also the IL that caused the problem should be show in commented form. (which would probably simplify trying to fix the root cause for these issues)

The CommentStatement approach can be useful for other things, such as changed code during decompile
Existing `WriteComment()` is more of a special case and not a statement.

```C#
        [Modifiers(Modifiers.Public | Modifiers.Static | Modifiers.Native)]
        public static void registerHook()
        {

Current member / type: System.Void com.xxx.javaclient.jni.JniInterfaceClass::registerHook()
File path: C:\dev\ikvm\JavaClient.exe

Product version: 2016.1.112.1
Exception in: System.Void registerHook()

Telerik.JustDecompiler.DecompilationException: Method pointer cannot be resolved to a method definition.
   vid Telerik.JustDecompiler.Decompiler.ExpressionDecompilerStep.OnCalli(Instruction instruction) i c:\Builds\245\Behemoth\ReleaseBranch Production Build\Sources\OpenSource\Cecil.Decompiler\Decompiler\ExpressionDecompilerStep.cs:rad 653
.....

mailto: JustDecompilePublicFeedback@telerik.com

        }
```

The code generated by dotPeek in this case...

```C#
    [Modifiers(Modifiers.Public | Modifiers.Static | Modifiers.Native)]
    public static void registerHook()
    {
      JNI.Frame frame = new JNI.Frame();
      if (JniInterfaceClass.__\u003Cjniptr\u003EregisterHook\u0028\u0029V == IntPtr.Zero)
        JniInterfaceClass.__\u003Cjniptr\u003EregisterHook\u0028\u0029V = JNI.Frame.GetFuncPtr(JniInterfaceClass.__\u003CGetCallerID\u003E(), "com/xxx/javaclient/jni/JniInterfaceClass", "registerHook", "()V");
      IntPtr num1 = frame.Enter(JniInterfaceClass.__\u003CGetCallerID\u003E());
      try
      {
        IntPtr num2 = num1;
        IntPtr num3 = frame.MakeLocalRef((object) ClassLiteral<JniInterfaceClass>.Value);
        // ISSUE: cast to a function pointer type
        // ISSUE: function pointer call
        __calli((__FnPtr<void (IntPtr, IntPtr)>) JniInterfaceClass.__\u003Cjniptr\u003EregisterHook\u0028\u0029V)(num2, num3);
      }
      catch (object ex)
      {
        System.Console.WriteLine((object) "*** exception in native code ***");
        System.Console.WriteLine(ex);
        throw;
      }
      finally
      {
        frame.Leave();
      }
    }
```

**Comment by NiKiZe** [comment]
Just to clarify, I'm looking for a more generic "fix" of all decompilation exceptions so atleast part of the method body is returned.

The Exception itself in this case is not important and just an example, even if it would be good to fix that as well ;)

**Comment by tsviatko** [comment]
Well the simple answer is JustDecompile does not do that because :

1. Code accuracy, i.e. full equivalence of generated code to MSIL in the assembly, has been a topmost priority ever since the beginning of the project. (The waste of end user time caused by inaccurate code is potentially huge.)
2. It is generally impossible to guarantee code accuracy without fully decompiling a member.

In your example nothing bad happens because of omitting the two IL statements. That, however, is not the general case. The omitted code might affect the other parts of the method by changing variable values (which will affect variable inlining later on which in turn affects a number of other decompilation steps that might change the code displayed) or by changing the control flow which will change the structure of the method and so on.

So we need some kind of automated analysis on the possible side effects of the piece of code we gave up on decompiling. Such an analysis is very likely to be theoretically impossible for the general case.

Of course we could do another analysis that recognizes the cases where we can analyse the side effects (like your example). Creating and maintaining this analysis as the decompilation code changes, though, would be a really time-consuming task taking in mind the sheer number of possibilities. The benefit from this task does not justify the overwhelming cost and that's why we never did it.

So, all in all, that's where we stand with the structured approach to this problem. I've never experimented with dotPeek to the extent to prove this but I am pretty sure that for the very same reasons stated above they don't guarantee code accuracy on methods where they have the //ISSUE comment.

**Comment by NiKiZe** [comment]
Still outputing the raw method IL as a commented should be better then only showing the internal obfuscated stacktrace from JustDecompile.

**Comment by tsviatko** [comment]
That might actually be true. It is a minor convenience, though, since switching to IL will produce the same result.
