### ISSUE TITLE
Is JustDecompile a dead project?

### ISSUE THREAD

**Issue by gsuberland** [telerik/JustDecompileEngine#52]
It's been over two years since the last commit here, and there hasn't been an update release since 2019. The update server also now seems to be dead, which causes an error on startup every time the program starts. Are there plans to pick the project back up, or is Telerik dropping the product? It'd be helpful to get an answer so that we can focus on other tools if development has halted permanently.

**Comment by tsviatko** [comment]
I am the original creator of JustDecompile and to the best of my knowledge no work has been done on it ever since the spring of 2018. It is up to Telerik to confirm that finally but for what I know they abandoned it after we split paths.

Me and the team of JustDecompile are now working on this - https://decompiler.codemerx.com/. It is based on this same engine but the UI should feel better and it also runs on Mac and Linux. So, you might want to try it out.

**Comment by gsuberland** [comment]
Thanks! Makes sense. I'll check that out.
